import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";


const inter = Inter({ subsets:['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content =(
    <p>Yo Yo</p>

  )
  return (
    <html lang="en">
      <body
        className={inter.className}
      > 
        <Navbar />
        {/* bug check pt-32 any value gt 32 does not shift the content down <div className="pt-42 bg-gray-700"> */}
        <div className="pt-32 ">
          {children}
        </div>

      </body>
    </html>
  );
}
